name: .NET workflow api project

# trigger
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    # self-hosted runner
    runs-on: self-hosted

    steps:

    # checkout source code at v2
    - uses: actions/checkout@v2

    # setup .net at v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        
    # clean 
    - name: clean previous dependencies
      run: dotnet clean

    # restore
    - name: restore dependencies
      run: dotnet restore

    # build - generate executable files (dll?)
    - name: build
      run: dotnet build --configuration Release --no-restore

    # test - is test required?
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    # unzip and connect to iis?
    # - name: iis website 
    #   uses: 
    #   with:
    #     website-name: 'api-project-iis'
    #     WebAppPoolName: "api-project-iis"

    # zip files
    # - name: publish
    #   run: dotnet publish --configuration Release

    # connect to iis again?
    # - name: iis website 
    #   uses: 
    #   with:
    #     website-name: 'api-project-iis'
    #     WebAppPoolName: "api-project-iis"
